[project]
name = "project-yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "lap>=0.5.12",
    "pytubefix>=9.5.1",
    "ultralytics>=8.3.202",
]
